### ISSUE TITLE
rhcs-coolstore-demo requires download that's not available

### ISSUE THREAD

**Issue by adietish** [redhatdemocentral/rhcs-coolstore-demo#7]
when running init.s for rhcs-coolstore-demo one is told to download jboss-brms-6.4.0.GA-deployable-eap7.x.zip:
```
Need to download jboss-brms-6.4.0.GA-deployable-eap7.x.zip package from https://developers.redhat.com/products/brms/download
```
But https://developers.redhat.com/products/brms/download doesnt offer this package, one can only see the following package:
* jboss-brms-6.4.0.GA-installer.jar

**Comment by adietish** [comment]
looks like this is my fault not taking extra care of the URL I'm watching at. Once logged in, looking at all downloads I only see the above package. If I really use the URL that the init script is suggesting I can see the download.

**Comment by eschabell** [comment]
Whew! :-)
